# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-11 10:36

import uuid

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_accounts.models.address
import django_accounts.models.file


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_accounts", "0001_initial"),
        ("django_accounts", "0002_customer_is_active"),
        ("django_accounts", "0003_alter_customer_uid"),
        ("django_accounts", "0004_socialloginproviders"),
        ("django_accounts", "0005_socialloginproviders_front_url"),
        ("django_accounts", "0006_delete_useraccount"),
        ("django_accounts", "0007_email_null"),
        ("django_accounts", "0008_remove_invoicedata_address_remove_address_email_and_more"),
        ("django_accounts", "0009_file_addressfile"),
        ("django_accounts", "0010_customer_external_id"),
        ("django_accounts", "0011_customer_extra"),
        ("django_accounts", "0012_address_external_id_address_source"),
        ("django_accounts", "0013_productrepresentation_wishlist_wishlistproduct_and_more"),
        ("django_accounts", "0014_wishlistproduct_modified_at"),
        ("django_accounts", "0015_group_customer_language_alter_address_customer_and_more"),
        ("django_accounts", "0016_alter_file_upload"),
        ("django_accounts", "0017_remove_address_data_for_company_can_not_be_null_and_more"),
        ("django_accounts", "0018_wishlistproduct_extra_alter_address_customer"),
        ("django_accounts", "0019_customerinmagento"),
        ("django_accounts", "0020_alter_address_source"),
        ("django_accounts", "0021_channel_socialloginproviders_channel"),
        ("django_accounts", "0022_alter_channel_options_customer_blacklist_channels_and_more"),
        ("django_accounts", "0023_remove_productrepresentation_unique_accounts_product_sku_in_channel_and_more"),
        ("django_accounts", "0024_mechanism_wishlist"),
        ("django_accounts", "0025_wishlistproduct_sources"),
        ("django_accounts", "0026_alter_customer_billing_address_and_more"),
        ("django_accounts", "0027_customer_last_session_country_and_more"),
        ("django_accounts", "0028_delete_customerinmagento"),
        ("django_accounts", "0029_apiadminkey"),
        ("django_accounts", "0030_socialloginproviders_allowed_origins"),
        ("django_accounts", "0031_alter_socialloginproviders_front_url"),
        ("django_accounts", "0032_customer_indexes"),
    ]

    # Data ops from the old chain intentionally not carried over (no-ops on a fresh database):
    # 0024_mechanism_wishlist backfilled existing Wishlist/ProductRepresentation rows per
    # MIGRATION_0023_MECHANISM; 0031_alter_socialloginproviders_front_url converted pre-existing
    # front_url strings to JSON. Both iterate over rows that cannot exist at install time.

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("django_regional", "0002_reset_pk_sequences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("firstname", models.CharField(blank=True, default=None, max_length=128, null=True)),
                ("lastname", models.CharField(blank=True, default=None, max_length=128, null=True)),
                ("street", models.CharField(blank=True, default="", max_length=128)),
                ("city", models.CharField(max_length=128)),
                ("postcode", models.CharField(max_length=32)),
                ("telephone", models.CharField(max_length=64)),
                ("dialling_code", models.CharField(default="", max_length=6)),
                ("country_code", models.CharField(default="", max_length=2)),
                ("company", models.CharField(blank=True, default=None, max_length=256, null=True)),
                ("is_company", models.BooleanField(default=False)),
                ("tax_id", models.CharField(blank=True, default=None, max_length=32, null=True)),
                (
                    "source",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Address source unknown"),
                            (1, "Address from PWA"),
                            (2, "Address from Magento2"),
                            (3, "Address from external source"),
                            (4, "Address from CSV"),
                        ],
                        default=django_accounts.models.address.AddressSourceEnum["PWA"],
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(blank=True, max_length=32, null=True)),
                ("area_code", models.CharField(blank=True, max_length=32, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(blank=True, max_length=32, null=True)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("extra", models.JSONField(blank=True, null=True)),
                ("last_session_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "billing_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_billing",
                        to="django_accounts.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(default="", max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserExtensionProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("label", models.CharField(default="", max_length=128, unique=True)),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Used for for social login.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_channels_accounts",
                        to="django_regional.language",
                        verbose_name="default language",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="APIAdminKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="django_accounts.channel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("default", "Default"), ("address_attachment", "Address Attachment")],
                        default="default",
                        max_length=128,
                    ),
                ),
                (
                    "upload",
                    models.FileField(
                        storage=django_accounts.models.file.customer_storage,
                        upload_to=django_accounts.models.file.customer_directory_path,
                    ),
                ),
                ("name", models.TextField(blank=True, default=None, null=True)),
                ("label", models.CharField(blank=True, default=None, max_length=256, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="django_accounts.customer",
                        verbose_name="customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="blacklist_channels",
            field=models.ManyToManyField(blank=True, related_name="customers_blacklist", to="django_accounts.channel"),
        ),
        migrations.AddField(
            model_name="customer",
            name="language",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_regional.language"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_session_country",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_regional.country"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_shipping",
                to="django_accounts.address",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="source_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers_source",
                to="django_accounts.channel",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="address",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="django_accounts.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_accounts.group"
            ),
        ),
        migrations.CreateModel(
            name="ProductRepresentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(db_index=True, max_length=128)),
                ("name_t9n", models.JSONField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts_products_representation_channel",
                        to="django_accounts.channel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products representations",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="Revoke",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SocialLoginProviders",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=False)),
                ("provider", models.CharField(choices=[("google", "Google"), ("facebook", "Facebook")], max_length=32)),
                ("name", models.CharField(blank=True, max_length=32, null=True)),
                ("client_id", models.CharField(max_length=256)),
                ("key", models.CharField(max_length=256)),
                ("callback_url", models.CharField(max_length=256)),
                (
                    "front_url",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Multilingual URLs, e.g. {"pl": "https://...", "en": "https://..."}',
                    ),
                ),
                (
                    "allowed_origins",
                    models.JSONField(
                        blank=True, default=list, help_text="Lista dozwolonych domen dla redirect_url, Lista: []"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="django_accounts.channel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Login - Provider",
                "verbose_name_plural": "Social Login - Providers",
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="django_accounts.channel",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_accounts.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WishlistProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_external", models.BooleanField(default=False)),
                ("sources", models.JSONField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django_accounts.productrepresentation"
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_accounts.wishlist"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wishlist",
            name="product",
            field=models.ManyToManyField(
                related_name="accounts_products",
                through="django_accounts.WishlistProduct",
                to="django_accounts.productrepresentation",
            ),
        ),
        migrations.CreateModel(
            name="AddressFile",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_accounts.file",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="django_accounts.address",
                        verbose_name="address",
                    ),
                ),
            ],
            bases=("django_accounts.file",),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("firstname__isnull", False), ("lastname__isnull", False)),
                    ("company__isnull", False),
                    _connector="OR",
                ),
                name="name_or_company_have_to_be_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_company", False),
                    models.Q(("company__isnull", False), ("tax_id__isnull", False)),
                    _connector="OR",
                ),
                name="data_for_company_can_not_be_null",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["-created_at"], name="django_acco_created_5431b8_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["is_active"], name="django_acco_is_acti_bf02b9_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["is_verified"], name="django_acco_is_veri_668be1_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["source_channel"], name="django_acco_source__af6f1d_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["group"], name="django_acco_group_i_c4ce15_idx"),
        ),
        migrations.AddConstraint(
            model_name="productrepresentation",
            constraint=models.UniqueConstraint(
                fields=("sku", "channel"), name="unique_product_representation_per_channel"
            ),
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(fields=("customer", "channel"), name="unique_wishlist_per_customer"),
        ),
    ]
